import Head from 'next/head'
import { Kumbh_Sans } from '@next/font/google'
import Header from '@/components/Header'
import Container from '@/components/Container'

const kumbh = Kumbh_Sans({ subsets: ['latin'], weight: ["400", "700"] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${kumbh.className}`}>
        <Header />
        <Container>
        </Container>
      </main>
    </>
  )
}
